@startuml
'https://plantuml.com/activity-diagram-beta

(*) --> [启动系统] "StartSystem"
 --> [发送消息] "DataCollectEvent"
 --> [接收消息] "DataCollectListener"
 --> [发送消息] "DataAnalyzeEvent"
 --> [接收消息] "DataAnalyzeListener"
 --> [发送消息] "EarlyWarningEvent"
 --> [接收消息] "EarlyWarningListener"

@enduml
