@startuml
'https://plantuml.com/activity-diagram-beta

(*) --> [启动系统] "StartSystem"
 --> [发送消息] "DataCollectEvent"
 --> [接收消息] "DataCollectListener"
 --> [发送消息] "DataAnalyzeEvent"
 -right-> [接收消息] "DataAnalyzeListener"
 -up-> [发送消息] "EarlyWarningEvent"
 -up-> [接收消息] "EarlyWarningListener"

@enduml
