@startuml
'https://plantuml.com/class-diagram

skinparam classAttributeIconSize 0
skinparam linetype ortho

Class DataCollectSystem{
- instance: DataCollectSystem
- DataCollectSystem()
+ getInstance(): DataCollectSystem
}

DataCollectSystem --> DataCollectSystem

Class DataAnalyzeSystem{
- instance: DataAnalyzeSystem
- DataAnalyzeSystem()
+ getInstance(): DataAnalyzeSystem
}

DataAnalyzeSystem --> DataAnalyzeSystem

Class EarlyWarningSystem{
- instance: EarlyWarningSystem
- EarlyWarningSystem()
+ getInstance(): EarlyWarningSystem
}

EarlyWarningSystem --> EarlyWarningSystem

@enduml